### ISSUE TITLE
Update data?

### ISSUE THREAD

**Issue by darrenleeweber** [spoqa/iso4217#3]
https://www.currency-iso.org/en/home/tables/table-a1.html

It was last updated `<ISO_4217 Pblshd="2018-06-04">`

The last commit on this was in 2016

Ideally, there could be a method to `update` the data from a URL.

**Comment by dahlia** [comment]
The data file is not added to the Git repository.  It's only included in the source tarballs or the wheels.

See also the latest release on the PyPI: <https://pypi.org/project/iso4217/1.5.20180604/>.
